spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://{ip}:5432/postgres
    username: postgres
    password: "***"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
openapi:
  service:
    api-docs: api-service
    server: ${API_URL:https://{ip}:7750}
    title: API-Service Documents
    version: 1.0.0

cors:
  allow:
    origins: http://localhost:8500