server:
  port: 8080
spring:
  application:
    name: api-service
  profiles:
    active: @spring.profiles.active@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

# Logging
logging:
  level:
    root: INFO
    org.springframework: OFF